<a href="https://colab.research.google.com/github/318245915/Reconocimiento-de-Patrones-y-Aprendizaje-Automatizado/blob/main/Pr%C3%A1ctica_2_M%C3%A9tricas_de_evaluaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from keras.datasets import mnist
import numpy as np

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Se obtiene una muestra con igual número de: cincos vs no cincos
# para el conjunto de entrenamiento y el de test
idx_y_train_5 = np.where(y_train == 5)[0]
idx_y_train_n5 = np.where(y_train != 5)[0]
idx_y_train_n5 = np.random.choice(idx_y_train_n5, idx_y_train_5.shape[0], replace=False)

idx_y_train = np.concatenate([idx_y_train_5, idx_y_train_n5])
np.random.shuffle(idx_y_train)

x_train = x_train[idx_y_train]
y_train = y_train[idx_y_train]
print(x_train.shape)

idx_y_test_5 = np.where(y_test == 5)[0]
idx_y_test_n5 = np.where(y_test != 5)[0]
idx_y_test_n5 = np.random.choice(idx_y_test_n5, idx_y_test_5.shape[0], replace=False)

idx_y_test = np.concatenate([idx_y_test_5, idx_y_test_n5])
np.random.shuffle(idx_y_test)

x_test = x_test[idx_y_test]
y_test = y_test[idx_y_test]
print(x_test.shape)

y_train_binary = (y_train == 5).astype(int)
y_test_binary = (y_test == 5).astype(int)

(10842, 28, 28)
(1784, 28, 28)


In [13]:
#EJERCICIO 1
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary())

model.compile(loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.9)

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_5 (Flatten)         (None, 784)               0         
                                                                 
 dense_5 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
1/1 [==============================] - 1s 676ms/step - loss: 7.1580 - accuracy: 0.5295 - val_loss: 7.0143 - val_accuracy: 0.5406
Epoch 2/4
1/1 [==============================] - 0s 57ms/step - loss: 7.1071 - accuracy: 0.5341 - val_loss: 7.0164 - val_accuracy: 0.5406
Epoch 3/4
1/1 [==============================] - 0s 48ms/step - loss: 7.1089 - accuracy: 0.5351 - val_loss: 6.5932 - val_accuracy: 0.5673


In [14]:
#EJERCICIO 1
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[344 548]
 [169 723]]
Precision_1: 0.5688434303697876
Recall_1: 0.8105381165919282
F1-score_1: 0.668515950069348
Precision_0: 0.6705653021442495
Recall_0: 0.38565022421524664
F1-score_0: 0.48967971530249105


In [4]:
#EJERCICIO 2
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary())

model.compile(loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train_binary, epochs=20, batch_size=2000, validation_split=0.9)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/20
1/1 [==============================] - 1s 1s/step - loss: 7.2062 - accuracy: 0.5277 - val_loss: 6.1638 - val_accuracy: 0.5983
Epoch 2/20
1/1 [==============================] - 0s 78ms/step - loss: 6.4899 - accuracy: 0.5756 - val_loss: 6.0658 - val_accuracy: 0.6028
Epoch 3/20
1/1 [==============================] - 0s 77ms/step - loss: 6.3981 - accuracy: 0.5821 - val_loss: 5.9681 - val_accuracy: 0.6081


In [5]:
#EJERCICIO 2
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[592 300]
 [175 717]]
Precision_1: 0.7050147492625368
Recall_1: 0.8038116591928252
F1-score_1: 0.751178627553693
Precision_0: 0.771838331160365
Recall_0: 0.6636771300448431
F1-score_0: 0.7136829415310427


In [6]:
#EJERCICIO 3
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary())

model.compile(loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train_binary, epochs=4, batch_size=2, validation_split=0.9)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
542/542 [==============================] - 12s 21ms/step - loss: 7.6951 - accuracy: 0.4954 - val_loss: 7.9658 - val_accuracy: 0.4776
Epoch 2/4
542/542 [==============================] - 7s 13ms/step - loss: 7.6583 - accuracy: 0.4972 - val_loss: 7.4330 - val_accuracy: 0.5122
Epoch 3/4
542/542 [==============================] - 6s 11ms/step - loss: 7.0135 - accuracy: 0.5406 - val_loss: 6.8875 - val_accur

In [7]:
#EJERCICIO 3
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[438 454]
 [236 656]]
Precision_1: 0.590990990990991
Recall_1: 0.7354260089686099
F1-score_1: 0.6553446553446552
Precision_0: 0.6498516320474778
Recall_0: 0.4910313901345291
F1-score_0: 0.5593869731800765


In [8]:
#EJERCICIO 4
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary())

model.compile(loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.01)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
6/6 [==============================] - 1s 91ms/step - loss: 9.0903 - accuracy: 0.4066 - val_loss: 10.2676 - val_accuracy: 0.3303
Epoch 2/4
6/6 [==============================] - 0s 38ms/step - loss: 7.6956 - accuracy: 0.4954 - val_loss: 8.1320 - val_accuracy: 0.4679
Epoch 3/4
6/6 [==============================] - 0s 22ms/step - loss: 7.0624 - accuracy: 0.5363 - val_loss: 7.4422 - val_accuracy: 0.5138


In [9]:
#EJERCICIO 4
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 2ms/step
Matriz de confusión:
[[261 631]
 [135 757]]
Precision_1: 0.5453890489913544
Recall_1: 0.8486547085201793
F1-score_1: 0.6640350877192981
Precision_0: 0.6590909090909091
Recall_0: 0.29260089686098656
F1-score_0: 0.40527950310559


In [10]:
#EJERCICIO 5
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary())

model.compile(loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train_binary, epochs=14, batch_size=30, validation_split=0.2)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/14
290/290 [==============================] - 1s 3ms/step - loss: 6.2457 - accuracy: 0.5932 - val_loss: 5.2800 - val_accuracy: 0.6556
Epoch 2/14
290/290 [==============================] - 1s 3ms/step - loss: 5.3174 - accuracy: 0.6538 - val_loss: 5.2698 - val_accuracy: 0.6570
Epoch 3/14
290/290 [==============================] - 1s 3ms/step - loss: 4.7434 - accuracy: 0.6902 - val_loss: 4.4351 - val_accura

In [11]:
#EJERCICIO 5
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)


precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 2ms/step
Matriz de confusión:
[[837  55]
 [161 731]]
Precision_1: 0.9300254452926209
Recall_1: 0.8195067264573991
F1-score_1: 0.8712753277711562
Precision_0: 0.8386773547094188
Recall_0: 0.9383408071748879
F1-score_0: 0.8857142857142856
